version: "3.8"

services:
  gmail-mcp:
    build:
      context: .
      dockerfile: Dockerfile.gmail-mcp
    container_name: gmail-mcp
    ports:
      - "3000:3000"
    volumes:
      - gcp-oauth:/root/.gmail-mcp       # holds your keys + generated tokens
    restart: unless-stopped

  voice-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: voice-assistant
    depends_on:
      - gmail-mcp
    env_file:
      - .env
    volumes:
      - ./:/app                          # so you can tweak code without rebuilding
    tty: true
    # For Linux audio, you can uncomment & tweak these:
    # devices:
    #   - "/dev/snd:/dev/snd"
    # environment:
    #   - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    # volumes:
    #   - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    #   - ~/.config/pulse/cookie:~/.config/pulse/cookie

volumes:
  gcp-oauth:
